// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LavadoraMVC.Models
{
    public partial class Empleados
    {
        public Empleados()
        {
            Lavados = new HashSet<Lavados>();
        }

        public int Id { get; set; }
        [Required(ErrorMessage = "El nombre es requerido")]
        [StringLength(50, ErrorMessage = "El valor {0} no puede superar los {1} caracteres. ")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "El celular es requerido")]
        [StringLength(10, ErrorMessage = "El valor {0} no puede superar los {1} caracteres. ",MinimumLength =10)]
        public string Celular { get; set; }

        public virtual ICollection<Lavados> Lavados { get; set; }
    }
}