// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LavadoraMVC.Models
{
    public partial class Lavados
    {
        public int Id { get; set; }
        public DateTime? FechaCreacion { get; set; }
        [Required(ErrorMessage = "La velocidad es requerida")]
        public int Velocidad { get; set; }
        [Required(ErrorMessage = "La calidad es requerida")]
        public int Calidad { get; set; }
        [Required(ErrorMessage = "La amabilidad es requerida")]
        public int Amabilidad { get; set; }
        public decimal Promedio { get; set; }
        [Required(ErrorMessage = "El empleado es requerido")]
        public int IdEmpleado { get; set; }
        public int IdCliente { get; set; }
        [Required(ErrorMessage = "El tipo de lavado es requerido")]
        public int IdTipoLavado { get; set; }

        public virtual Usuarios IdClienteNavigation { get; set; }
        public virtual Empleados IdEmpleadoNavigation { get; set; }
        public virtual TipoLavados IdTipoLavadoNavigation { get; set; }
    }
}