// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LavadoraMVC.Models
{
    public partial class TipoLavados
    {
        public TipoLavados()
        {
            Lavados = new HashSet<Lavados>();
        }

        public int Id { get; set; }
        [Required(ErrorMessage = "La descripción es requerido")]
        [StringLength(100, ErrorMessage = "El valor {0} no puede superar los {1} caracteres. ")]
        public string Descripcion { get; set; }

        public virtual ICollection<Lavados> Lavados { get; set; }
    }
}